version: "3"
services:
  upload_service:
    build: ./upload_service
    ports:
      - "8001:8001"
    volumes:
      - ./uploads:/app/uploads
  metadata_service:
    build: ./metadata_service
    ports:
      - "8002:8002"
    volumes:
      - ./metadata:/app/metadata
  download_service:
    build: ./download_service
    ports:
      - "8003:8003"
    volumes:
      - ./uploads:/app/uploads # Make sure this is consistent with upload service
