services:
  upload_service:
    build: ./upload_service
    ports:
      - "8001:8001"
    depends_on:
      - metadata_service

  metadata_service:
    build: ./metadata_service
    ports:
      - "8002:8002"

  download_service:
    build: ./download_service
    ports:
      - "8003:8003"
    depends_on:
      - metadata_service
